opam-version: "2.0"
license: "MIT"
maintainer: "Tej Chajed"
authors: "Tej Chajed <chajed@wisc.edu>"
homepage: "https://github.com/tchajed/sys-verif-solutions"
bug-reports: "https://github.com/tchajed/sys-verif-solutions/issues"
dev-repo: "git+https://github.com/tchajed/sys-verif-solutions.git"
version: "dev"
synopsis: "Systems verification course material"

depends: [
  "perennial"
]

pin-depends: [
  ["perennial.dev"             "git+https://github.com/mit-pdos/perennial#23aff1832c9b3aa2a5421be9b0fbac4b591afc14"]

  ## begin indirect
  ["coq-coqutil.dev"           "git+https://github.com/mit-plv/coqutil#6644c132300a4da5fb1a4ce5c3860f60c135b2fa"]
  ["coq-record-update.dev"     "git+https://github.com/tchajed/coq-record-update#7b2645210331c3ec4ed75fa5ad0840a723f25151"]
  ["iris-named-props.dev"      "git+https://github.com/tchajed/iris-named-props#c388714a93b1c043ed42a3f446280abd5113d26f"]
  ["rocq-iris.dev"             "git+https://gitlab.mpi-sws.org/iris/iris#b641d1560959d4f3052d84daaac4047c99416c4c"]
  ["rocq-stdpp.dev"            "git+https://gitlab.mpi-sws.org/iris/stdpp#0989202c46f352854feb5f96b6c3a1f4f91f886a"]
  ## end
]

build: [make "-j%{jobs}%"]
install: ["perennial-cli" "install"]
